blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('category/<str:slug>/', views.category_page), #IP주소/blog/category/slug/
    path('tag/<str:slug>/', views.tag_page), #IP주소/blog/tag/slug/
    path('search/<str:q>/', views.PostSearch.as_view())

    # path('',views.index),  #IP주소/blog  #views 연결하기  #.index : 함수명
    # path('<int:pk>/', views.single_post_page)   #int형으로 옴 , 타입은 pk로,
]

myDjangoPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  #IP주소/admin
    path('blog/', include('blog.urls')), #blog 폴더에 있는 urls를 불러오기  #IP주소/blog
    path('', include('single_pages.urls')),  #IP주소/
    path('accounts/', include('allauth.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Model이 변경될 때 마다 꼭 해주기!!!
# python manage.py makemigrations
# python manage.py migrate

class Tag(models.Model):
    name=models.CharField(max_length=50, unique=True)
    slug=models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


class Category(models.Model):
    name=models.CharField(max_length=50, unique=True)
    slug=models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'
    class Meta:
        verbose_name_plural='Categories'

class Post(models.Model): #Post 모델 생성
    title=models.CharField(max_length=30) #Post 모델의 필드 생성  #CharField():길이 제한을 해줄 때
    hook_text=models.CharField(max_length=100,blank=True) #사용자가 미리보기 제공 안해도 ok
    content=models.TextField()            #TextField():길이 제한 없을 때

    head_image=models.ImageField(upload_to='blog/images/%Y/%m/%d/',blank=True)
    #%Y 2022(4자리) / %y 22(2자리)
    file_upload=models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    #한국 시간에 맞추기 위해서는 '프로젝트 - settings.py'에서 TIME_ZONE = 'Asia/Seoul', USE_TZ = False 로 작성해주기
    created_at=models.DateTimeField(auto_now_add=True)  #DateTimeField:날짜, 시간   auto_now_add=True:자동으로 시간 부여
    updated_at=models.DateTimeField(auto_now=True)

    #추후 author 작성
    author=models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category=models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags=models.ManyToManyField(Tag, blank=True)

    def __str__(self):  #Model안의 내용을 화면에 출력하는 기능
        return f'[{self.pk}]{self.title}::{self.author}:{self.created_at}'  #게시글을 만들 때 마다 고유의 키를 부여함 -> pk(primary key)

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'   #문자열 만들기

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)  #파일명만 가져오기

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]  #split('.') : .으로 구분하기
        # 배열이니 a가 [0]번지, txt가 [1]번지
        # a.txt  -> a txt
        # b.docx -> b docx
        # c.xlsx -> c xlsx
        # 하지만 a.b.c.txt -> a b c txt  1번지로 하면 b이니 마지막에 있는 것으로 지정하기 [-1]

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('content',)

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

#CBV 사용했을 때
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields=['title','hook_text', 'content','head_image','file_upload','category'] #,'tags'

    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user==self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form): #여기 수정 필요 있음 11.10 2:37
        response = super(PostUpdate, self).form_valid(form)
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list=list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tage_str_default'] = ';'.join(tags_str_list)
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model=Post
    fields=['title','hook_text', 'content','head_image','file_upload','category'] #,'tags'
    #템플릿은 post_forms

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


    def form_valid(self, form):
        current_user=self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author=current_user
            response=super(PostCreate, self).form_valid(form)
            tags_str=self.request.POST.get('tags_str')
            if tags_str:
                tags_str=tags_str.strip()
                tags_str=tags_str.replace(',',';')
                tags_list=tags_str.split(';')
                for t in tags_list:
                    t=t.strip()
                    tag, is_tag_created=Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug=slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')


    #템플릿 : 모델명_form.html
    def get_context_data(self, *, object_list=None, **kwargs):
        context=super(PostCreate, self).get_context_data()
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count
        return context


class PostList(ListView):
    model=Post
    ordering = '-pk'
    paginate_by = 5
    # 템플릿 모델명_list.html : post_list.html4
    # 파라미터 모델명_list : post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super(PostList, self).get_context_data()
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count
        return context


class PostSearch(PostList):  # ListView 상속, post_list, post_list.html
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)|Q(tags__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info']=f'Search: {q} ({self.get_queryset().count()})'
        return context

class PostDetail(DetailView):
    model=Post
    # 템플릿 모델명_detail.html : post_detail.html
    # 파라미터 모델명 : post

    def get_context_data(self, **kwargs):
        context=super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['comment_form'] = CommentForm
        return context


def category_page(request, slug):
    if slug=='no_category' :
        category ='미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category=Category.objects.get(slug=slug)
        post_list=Post.objects.filter(category=category)
    return render(request, 'blog/post_list.html',{
        'category':category,
        'post_list':post_list,
        'categories':Category.objects.all(),
        'no_category_post_count':Post.objects.filter(category=None).count
    })

def tag_page(request, slug):
    tag=Tag.objects.get(slug=slug)
    post_list=tag.post_set
    return render(request, 'blog/post_list.html', {
        'tag':tag,
        'post_list':post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post=post
                comment.author=request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else: #GET
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    #CreateView, UpdateView, form을 사용하면
    #텝플릿 모델명_forms : comment_form 이 자동으로 생성

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user==self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied





#FBV 사용했을 때
# def index(request):
#     posts1=Post.objects.all().order_by('-pk');  # -pk : 역순으로 #Post 모델에 있는 모든 것들을 posts1에 넣음 -> 템플릿에서 사용된 데이터를 views에서 준비
#     return render(request, 'blog/index.html', {'posts':posts1})  #두번째 인자는 template 폴더에서 찾음  #오른쪽 posts1가 위에서 선언한 posts1

# def single_post_page(request,pk):  #pk에 따라 불러오는 글이 달라지니 views 쪽에 pk도 전달해야 함
#     post2=Post.objects.get(pk=pk)  #get : 특정한 거만 가져오기  #Post가 가지고 있는 필드 이름=위에서 받은 인자
#     return render(request,'blog/single_post_page.html',{'post':post2})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block head_title %}Blog{% endblock %}</title>  <!--title도 바뀌는 것이니 block으로 넣어주기 / post_detail에만 선언해줌-->
	<link href="{% static 'blog/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
	<script src="https://kit.fontawesome.com/87c08dff42.js" crossorigin="anonymous"></script>
</head>

<body>
	{% include 'blog/navbar.html' %}  <!--navbar 추가하기-->

	<div class="container">
		<div class="row">
			<div class="col-md-8 col-lg-9" id="main-area">
				{% block main_area %} <!--main_area 지워주고 block으로 넣어주기 -->
                {% endblock %}  <!--block내용은 post_detail, post_list에 있음 -->
			</div>
			<div class="col-md-4 col-lg-3">
				{% include 'blog/sidebar.html' %}
			</div>
		</div>
	</div>
	{% include 'blog/footer.html' %}

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Blog
{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/footer.html
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p>
		</div>
	</footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    {% for p in posts %} <!--views에서 왼쪽에 있는 posts -->
        <h2> <a href="{{p.get_absolute_url}}"> {{p.title}} </a> </h2>  <!-- 데베에 글이 3개 있어서 3번 반복-->
        <h3> {{p.created_at}} </h3>
        <p> {{p.content}} </p>
    {% endfor %}
</body>
</html>

blog/templates/blog/navbar.html
{% load socialaccount %}

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container">
			<a class="navbar-brand" href="/">Kabeen's IT</a> <!--href값 urels.py 참고해서 수정해주기-->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
				aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					<li class="nav-item active">
						<a class="nav-link" href="/">Home</a> <!--href값 urels.py 참고해서 수정해주기-->
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/blog/">Blog</a> <!--href값 urels.py 참고해서 수정해주기-->
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/about_me/">AboutMe</a> <!--href값 urels.py 참고해서 수정해주기-->
					</li>

				</ul>
				<ul class="navbar-nav ml-auto">
					{% if user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							{% if user.socialaccount_set.all.0.get_avatar_url %}
								<img class="rounded-circle mr-3" src="{{user.socialaccount_set.all.0.get_avatar_url}}" width="25px">
							{% else %}
								<img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" width="25px">
							{% endif %}
							{{user.username}}
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="/accounts/logout/">LogOut</a>
						</div>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Login</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>


	<!-- Modal -->
	<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-arrow-right-from-bracket"></i> LogIn</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-6">
							<a role="button" class="btn btn-outline-dark btn-block btn-sm"
								href="{% provider_login_url 'google' %}">
								<i class="fa-brands fa-google"></i>LogIn with Google
							</a>
							<a role="button" class="btn btn-outline-dark btn-block btn-sm"
								href="/accounts/login/">
								<i class="fa-regular fa-envelope"></i>LogIn with Email
							</a>
						</div>
						<div class="col-6">
							<a role="button" class="btn btn-outline-dark btn-block btn-sm"
								href="/accounts/signup/">
								<i class="fa-regular fa-envelope"></i>SignUp with Email
							</a>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{post.title}} - Blog
{% endblock %}

{% block main_area %}
                    <!-- Post content-->
                        <!-- Post header-->
                    <div>
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{post.title | lower}}</h1>  <!--lower : 소문자로 출력하기  -->
                            {% if post.hook_text %}
                            <h5 class="text-muted">{{post.hook_text}}</h5>
                            {% endif %}
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">
                                Posted on {{post.created_at | date:"Y-m-d h:m:s"}} by {{post.author|upper}}
                            </div>
                            <!-- Post categories-->
                            {% if post.category %}
                                <a class="badge bg-secondary text-decoration-none link-light" href="{{post.category.get_absolute_url}}">
                                    {{post.category}}
                                </a>
                            {% else %}
                                <a class="badge bg-secondary text-decoration-none link-light" href="/blog/category/no_category/">
                                    미분류
                                </a>
                            {% endif %}
                        </header>
                        {% if user.is_authenticated and user == post.author %}
                            <a href="/blog/update_post/{{post.pk}}" role="button" class="btn btn-info btn-sm float-right">
                            <i class="fas fa-pen"></i> Edit Post
                            </a>
                        {% endif %}
                        <!-- Preview image figure-->
                        <figure class="mb-4">
                            {% if post.head_image %}
                            <img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{post.title}}"의 head_image />
                            {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/200" alt="random image"/>
                            {% endif %}
                        </figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{post.content}}</p>
                            {% if post.tags.exists %}
								<i class="fas fa-tag"></i>
								{% for t in post.tags.iterator %}
									<span class="badge badge-pill badge-light">
                                        <a href="{{t.get_absolute_url}}">{{t}}</a>
                                    </span>
								{% endfor %}
							<br><br>
							{% endif %}
                            {% if post.file_upload %}
                            <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>  <!--download 역할을 한다-->
                                {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="fa-regular fa-file-excel"></i>
                                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                                <i class="fa-regular fa-file-word"></i>
                                {% else %}
                                <i class="fa-regular fa-file"></i>
                                {% endif %}
                                Download {{post.get_file_name}}
                            </a>
                            {% endif %}
                        </section>
                    </div>
                    <!-- Comments는 추후 작성할 예정-->
                    <!-- Comments section-->
                    <div id="comment-area" class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="post"
                                    action="{{post.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{comment_form | crispy}}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                {% else %}
                                    <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                                        data-toggle="modal" data-target="#loginModal">
                                        Login and Leave a comment
                                    </a>
                                {% endif %}
                                {% if post.comment_set.exists %}
                                {% for comment in post.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex" id="comment-{{comment.pk}}">

                                    <img class="mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px"/>
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                            <a role="button" class="btn btn-sm btn-info float-right"
                                               href="/blog/update_comment/{{comment.pk}}/">
                                                Edit
                                            </a>
                                        {% endif %}
                                        <div class="fw-bold">
                                            {{comment.author.username}}
                                            <small class="text-muted">{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks}}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class="text-muted float-right">
                                                <small>Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Craet New Post</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input type="text" id="id_tags" name="tags_str"
                    class="textinput textInput form-control">
            </div>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Post - Blog
{% endblock %}

{% block main_area %}
    <h1>Update Post</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input type="text" id="id_tags" name="tags_str" value="{{tage_str_default}}"
                    class="textinput textInput form-control">
            </div>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/sidebar.html
                <!-- Search widget-->
				<div class="card mb-4">
					<div class="card-header"><i class="fa-solid fa-magnifying-glass"></i> Search</div>
					<div class="card-body">
						<div class="input-group">
							<input id="search-input" class="form-control" type="text" placeholder="Enter search term..."
								aria-label="Enter search term..." aria-describedby="button-search" />
							<button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
						</div>
					</div>
				</div>
				<script>
					function searchPost(){
						searchValue=document.getElementById('search-input').value.trim();
						if(searchValue.length>1){
							location.href="/blog/search/"+ searchValue+"/";
						}
						else{
							alert('검색어('+searchValue+')가 너무 짧아요');
						}
					};

					document.getElementById('search-input').addEventListener(
						'keyup', function(event){
							if(event.key==='Enter'){
								searchPost()
							}
						});
				</script>
				<!-- Categories widget-->
				<div class="card mb-4" id="category-card">
					<div class="card-header">Categories</div>
					<div class="card-body">
						<div class="row">
							<ul class="list-unstyled mb-0">
								{% for c in categories %}
									<li><a href="{{c.get_absolute_url}}">{{c}} ({{c.post_set.count}})</a></li>
								{% endfor %}
									<li><a href="/blog/category/no_category">미분류 ({{no_category_post_count}})</a></li>
							</ul>
						</div>
					</div>
				</div>

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <h3>{{post.created_at}}</h3>
    <p>{{post.content}}</p>

    <hr />
    <h4>여기에 댓글을 넣으면 되겠죠?</h4>
</body>
</html>